### ISSUE TITLE
rknn.build failure at Global Average Pool input height/width > 128

### ISSUE THREAD

**Issue by ynjiun** [rockchip-linux/rknn-toolkit2#10]
I am running rknn toolkit for building a model.rknn for running on RK3566.
After rknn.load_onnx() successfully, when run rknn.build(), the following error message occur:

    --> Loading model: ./rknn_models/model_3566.onnx done
    --> Building model E build: Global Average Pool input height/width > 128, which is not suppoted! E build: Catch exception when building RKNN model! E build: Traceback (most recent call last): E build:   File "rknn/api/rknn_base.py", line 2621, in rknn.api.rknn_base.RKNNBase.build E build:   File "rknn/api/graph_optimizer.py", line 3765, in rknn.api.graph_optimizer.GraphOptimizer.run E build:   File "rknn/api/graph_optimizer.py", line 3518, in rknn.api.graph_optimizer.GraphOptimizer._fuse_ops E build:   File "rknn/api/graph_optimizer.py", line 2210, in rknn.api.graph_optimizer._p_convert_global_avgpool_to_conv E build:   File "rknn/api/rknn_log.py", line 104, in rknn.api.rknn_log.RKNNLog.e E build: ValueError: Global Average Pool input height/width > 128, which is not suppoted! Build pytorch failed!

I checked my source code, I did not use the Global Average Pool anywhere. And actually I did explicitly remove final two layers of basenet (efficientnet) which contains global_pool by assigning them as Identity as below:

       basemodel_name = 'tf_efficientnet_b5_ap'
        print('Loading base model ()...'.format(basemodel_name), end='')
        basemodel = torch.hub.load('rwightman/gen-efficientnet-pytorch', basemodel_name, pretrained=True)
        print('Done.')

        # Remove last layer
        print('Removing last two layers (global_pool & classifier).')
        basemodel.global_pool = nn.Identity()
        basemodel.classifier = nn.Identity()

So it puzzled me why the rknn.build() would complain about the Global Average Pool at all.

Could anyone help to point me to the potential causes and possible fixes? 

Thanks a lot for your help in advance.

**Comment by rkchrome** [comment]
Global avgpool input height/width support > 128 now for new version 1.2.0, but still should < 343

**Comment by ynjiun** [comment]
@rkchrome 

Thank you so much for your update. I tried it and it looks like it's making a big progress on my test model. However, this time got stuck at "Fatal: Meet unsupported operator: Sqrt(name="Sqrt_941")."

The error messages as below:
```
(rknn2) paul@tensor:~/pytorch/AdaBins$ python rk3566onnx.py 
right after import torch....
W __init__: rknn-toolkit2 version: 1.2.0-f7bb160f
--> config model
done
--> Loading model: ./rknn_models/model_3566.onnx
done
--> Building model
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
W build: Global Average Pool input height/width > 343, which is not suppoted!
Analysing :   0%|                                                           | 0/
Analysing :  34%|███████████████▉                               | 262/770 [00:00
Analysing :  52%|████████████████████████▍                      | 400/770 [00:00
Analysing :  65%|██████████████████████████████▎                | 497/770 [00:00
Analysing :  77%|████████████████████████████████████▊           | 590/770 [00:0
Analysing : 100%|███████████████████████████████████████████████| 770/770 [00:00<00:00, 1067.81it/s]
I RKNN: librknnc version: 1.2.0 (b162fe95e@2022-01-14T14:12:38)
D RKNN: [11:23:26.989] RKNN is invoked
Fatal: Meet unsupported operator: Sqrt(name="Sqrt_941").
```

It seems that it cannot build because rknn does not support "Sqrt" operator.

Please advise how to fix this issue. Thanks a lot.

**Comment by HunterRockchips** [comment]
Sqrt is not supported temporarily

**Comment by ynjiun** [comment]
Do we know when Sqrt well be supported? Thank you.

**Comment by HunterRockchips** [comment]
> Do we know when Sqrt well be supported? Thank you.

Sqrt may be supported on next format release version as soon.
If you need Sqrt in LayerNorm, maybe next version will open graph-optimization for it.

**Comment by ynjiun** [comment]
@HunterRockchips, 

I upgrade to the latest version 1.3.0 and indeed the Sqrt error is gone! Thank you very much.

But now I encounter the following error:

`Fatal: Meet unsupported operator: CumSum(name="CumSum_1274").`

When would the CumSum operator would be supported? or What command I can change in my code to avoid this unsupported error?

Thanks a lot for your help.

**Comment by HunterRockchips** [comment]
This op(CumSum) is not in develop plan. I suggest you change you graph with other operators which had supported.

**Comment by dongqianzhuan** [comment]
> @HunterRockchips,
> 
> I upgrade to the latest version 1.3.0 and indeed the Sqrt error is gone! Thank you very much.
> 
> But now I encounter the following error:
> 
> `Fatal: Meet unsupported operator: CumSum(name="CumSum_1274").`
> 
> When would the CumSum operator would be supported? or What command I can change in my code to avoid this unsupported error?
> 
> Thanks a lot for your help.

meet the same question 

I rknn building ...
I RKNN: librknnc version: 1.3.0 (c193be371@2022-05-04T20:23:58)
D RKNN: [10:47:53.678] RKNN is invoked
Fatal: Meet unsupported operator: Sqrt(name="Sqrt_51").

to:rockchip
sqrt not supportin rknn2 1.3version,please add the op in it next version

**Comment by ynjiun** [comment]
@HunterRockchips 

After I replace torch.cumsum with equivalent python code in my model, now it encounters a new unsupported operator:
`Fatal: Meet unsupported operator: ScatterND(name="ScatterND_1308").`
So are we going to add "ScatterND" op soon?
Thank you.

**Comment by HunterRockchips** [comment]
Temporarily not. Maybe Sqrt will support quicker.

**Comment by HunterRockchips** [comment]
Or, you can cut the model into 2 pieces, and execute this op by cpu.
