### ISSUE TITLE
rknn_toolkit_lite2的examples执行出错

### ISSUE THREAD

**Issue by aininot260** [rockchip-linux/rknn-toolkit2#119]
代码在
https://github.com/rockchip-linux/rknn-toolkit2/tree/master/rknn_toolkit_lite2/examples/inference_with_lite
未改动

rknn_toolkit_lite2用的版本是1.4.0
模组是TB-RK3588

报错信息为：
`toybrick@debian:~/Desktop/rknn_toolkit_lite2/examples/inference_with_lite$ python3 test.py
--> Load RKNN model
done
--> Init runtime environment
I RKNN: [11:40:07.311] RKNN Driver Information: version: 0.6.4
I RKNN: [11:40:07.311] RKNN Runtime Information: librknnrt version: 1.2.1b5 (fc044714f@2022-02-22T14:48:33)
E RKNN: [11:40:07.311] parseRKNN from buffer: Invalid RKNN format!
E RKNN: [11:40:07.311] rknn_init, load model failed!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/toybrick/.local/lib/python3.9/site-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 840, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

Init runtime environment failed`

**Comment by ZhuoQian111** [comment]
我得到了相同的错误，希望能够给出solution

**Comment by lixunhui** [comment]
我得到了相同的错误，希望能够给出solution

**Comment by BigerPatax** [comment]
用sudo运行试试
