### ISSUE TITLE
yolov5的demo中预测报错

### ISSUE THREAD

**Issue by charming2992** [rockchip-linux/rknn-toolkit2#120]
训练的自己的数据集，CLASSES已经修改了。

Traceback (most recent call last):
  File "test.py", line 316, in <module>
    boxes, classes, scores = yolov5_post_process(input_data)
  File "test.py", line 157, in yolov5_post_process
    b, c, s = process(input, mask, anchors)
  File "test.py", line 64, in process
    col = col.reshape(grid_h, grid_w, 1, 1).repeat(3, axis=-2)
ValueError: cannot reshape array of size 64 into shape (80,8,1,1)

**Comment by charming2992** [comment]
> 训练的自己的数据集，CLASSES已经修改了。
> 
> Traceback (most recent call last): File "test.py", line 316, in boxes, classes, scores = yolov5_post_process(input_data) File "test.py", line 157, in yolov5_post_process b, c, s = process(input, mask, anchors) File "test.py", line 64, in process col = col.reshape(grid_h, grid_w, 1, 1).repeat(3, axis=-2) ValueError: cannot reshape array of size 64 into shape (80,8,1,1)

这个问题大概是toolkit和toolkit2中的这代码部分不一致，修改成toolkit中的就行如下图
![image](https://user-images.githubusercontent.com/106571854/219570040-3e689f8a-ff3b-40bd-9fcf-f75ac47f55fe.png)

**Comment by charming2992** [comment]
出现了另外一个问题，这个函数输出的boxes有两千多个，没有经过nms，并且classes也大于自己设定的类别数
boxes, classes, scores = yolov5_post_process(input_data)

**Comment by nullgogo** [comment]
有解决吗，我也遇到了相同问题
