### ISSUE TITLE
torchscript模型和onnx模型转rknn模型报错

### ISSUE THREAD

**Issue by ohnlily** [rockchip-linux/rknn-toolkit2#121]
**Torchscript模型报错**
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
I Save log info to: ./mobilenet_build.log
PtParse: 100%|████████████████████████████████████████████████| 1381/1381 [00:00<00:00, 1979.37it/s]
W load_pytorch: The config.mean_values is None, zeros will be set for input 0!
W load_pytorch: The config.mean_values is None, zeros will be set for input 1!
W load_pytorch: The config.std_values is None, ones will be set for input 1!
W load_pytorch: The config.mean_values is None, zeros will be set for input 2!
W load_pytorch: The config.std_values is None, ones will be set for input 2!
W load_pytorch: The config.mean_values is None, zeros will be set for input 3!
W load_pytorch: The config.std_values is None, ones will be set for input 3!
W load_pytorch: The config.mean_values is None, zeros will be set for input 4!
W load_pytorch: The config.std_values is None, ones will be set for input 4!
load onnx success
I base_optimize ...
I base_optimize done.
I
I fold_constant ...
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1541, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 636, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
E build: KeyError: 'mean'

**Onnx模型的报错**
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
I Save log info to: ./mobilenet_build.log
E load_onnx: Catch exception when loading onnx model: /model_trans/rvm_mobilenetv3_fp32.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1152, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 617, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx: TypeError: '<=' not supported between instances of 'NoneType' and 'int'

**Comment by ohnlily** [comment]
**TorchScript模型的代码**
rknn = RKNN(verbose=True, verbose_file='./mobilenet_build.log')
rknn.config(
    std_values=[[255., 255., 255.]],
            quant_img_RGB2BGR=False,
            target_platform='rk3588',
            single_core_mode=False)
input_size_list = [[1, 3, 240, 320], [1, 16, 120, 160], [1, 20, 60, 80], [1, 40, 30, 40], [1, 64, 15, 20]]
ret = rknn.load_pytorch(model="rvm_mobilenetv3_fp32.pt", input_size_list=input_size_list)
if ret == -1:
    print("load onnx error")
else:
    print("load onnx success")

**Onnx模型的代码**
rknn = RKNN(verbose=True, verbose_file='./mobilenet_build.log')
rknn.config(
    std_values=[[255., 255., 255.]],
            quant_img_RGB2BGR=False,
            target_platform='rk3588',
            single_core_mode=False)
ret = rknn.load_onnx(model="rvm_mobilenetv3_fp32.onnx")
if ret == -1:
    print("load onnx error")
else:
    print("load onnx success")

**Comment by fengge123** [comment]
我也遇到了同样的问题, 你的解决了吗
