### ISSUE TITLE
Not support input data type 'float16'!

### ISSUE THREAD

**Issue by nicolausYes** [rockchip-linux/rknn-toolkit2#128]
There's 'Not support input data type 'float16'!' during onnx model conversion.
The target platform is rk3588.

The working environment is Ubuntu 20.04.5, Python 3.8.10, rknn-toolkit2 1.4.0.
Onnx model.
https://drive.google.com/file/d/10XXfcqcM81eAO7iE1t8UgSrASAaHov8l/view?usp=sharing

Conversion code.

<pre><code class="python">
import numpy as np
import os
import urllib
import tarfile
import shutil
import traceback
import time
import sys
from rknn.api import RKNN

# Create RKNN object
rknn = RKNN(verbose=True)

# pre-process config
print('--> Config model')
rknn.config(target_platform='rk3588')
print('done')

print('--> Loading model')
ret = rknn.load_onnx(model = './supercombo_big.onnx')
if ret != 0:
    print('Load failed!')
    exit(ret)
print('done')

# Build model
print('--> Building model')
ret = rknn.build(do_quantization=False)
if ret != 0:
    print('Build *.rknn failed!')
    exit(ret)
print('done')

# Export rknn model
print('--> Export RKNN model')
ret = rknn.export_rknn("supercombo_big.rknn")
if ret != 0:
    print('Export *.rknn failed!')
    exit(ret)
print('done')
</code></pre>

Error.
> W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
> --> Config model
> done
> --> Loading model
> W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 10!
> W load_onnx: Model converted from pytorch, 'opset_version' should be set 12 in torch.onnx.export for successful convert!
> More details can be found in examples/pytorch/resnet18_export_onnx
> done
> --> Building model
> I base_optimize ...
> I base_optimize done.
> I
> I fold_constant ...
> E build: Not support input data type 'float16'!
> W build: ===================== WARN(3) =====================
> E rknn-toolkit2 version: 1.4.0-22dcfef4
> E build: Catch exception when building RKNN model!
> E build: Traceback (most recent call last):
> E build:   File "rknn/api/rknn_base.py", line 1541, in rknn.api.rknn_base.RKNNBase.build
> E build:   File "rknn/api/graph_optimizer.py", line 635, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
> E build:   File "rknn/api/load_checker.py", line 68, in rknn.api.load_checker.create_random_data
> E build:   File "rknn/api/rknn_log.py", line 113, in rknn.api.rknn_log.RKNNLog.e
> E build: ValueError: Not support input data type 'float16'!
> Build *.rknn failed!

**Comment by neocoretechs** [comment]
Interesting because I tried to export yoloV8s without quantization and it created Float16 data types!

**Comment by nicolausYes** [comment]
> Interesting because I tried to export yoloV8s without quantization and it created Float16 data types!

I've already got response from rockchip, that float16 is not supported and there are no plans for support :/

**Comment by thusinh1969** [comment]
This RKNN is so **premature** to go to market !!!!

**Comment by phhusson** [comment]
If you look at RKNN TRM https://github.com/Hao-boyan/rk3588-TRM-and-Datasheet/blob/master/Rockchip%20RK3588%20TRM%20V1.0-Part1-20220309.pdf you actually understand that it's not a completely generic NPU.

RKNN is pretty much a fixed pipeline for CNN + average/min/max pooling + ALU + batch normalisation + RELU. If you make your models taking this into account, you shouldn't have too much issues

According to TRM HW do support float 16, so I'm not sure why it wouldn't work, and as mentioned, rknn libs by default downgrades  everything to float16 (or i'm mistaken and it's actually bflot16?)

**Comment by neocoretechs** [comment]
Nope, verbose mode of the toolkit conversion explicitly states datatype, and that type is FLOAT16

**Comment by neocoretechs** [comment]
I think in the case of opset 10, it warned that opset 12 is needed, and its possible that under opset 10, float16 is not valid?

**Comment by neocoretechs** [comment]
> This RKNN is so **premature** to go to market !!!!

How do you say "caveat emptor" in chinese?

**Comment by ttxida** [comment]
> 

How do you think about bfloat16 ?
