### ISSUE TITLE
 rknn_toolkit2*cp38*.whl: No module named 'numpy' 

### ISSUE THREAD

**Issue by sarranetor** [rockchip-linux/rknn-toolkit2#144]
I am installing rknn_toolkit2 on Ubuntu 20.4.03 LS with python 3.8. I set the virtual environment with all package required, but when u run "sudo pip3 install packages/rknn_toolkit2*cp38*.whl" I get this error:

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dbegbkbb/bfloat16/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dbegbkbb/bfloat16/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dbegbkbb/bfloat16/pip-egg-info
         cwd: /tmp/pip-install-dbegbkbb/bfloat16/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dbegbkbb/bfloat16/setup.py", line 10, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

when i import bfloat16 from python it works fine.

**Comment by sarranetor** [comment]
I just tried with the 1.3.0 "sudo pip3 install packages/rknn_toolkit2*cp38*.whl" version with python 3.8 and ubuntu 20.4: 
Same Issue, No Module named numpy ..

**Comment by hlacikd** [comment]
run pip3 install numpy==1.19.5
