### ISSUE TITLE
在3588上使用docker,调用不了GPU，是不支持这种操作吗？

### ISSUE THREAD

**Issue by lkllk** [rockchip-linux/rknn-toolkit2#153]
--> Load RKNN model
done
--> Init runtime environment
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/rknnlite/api/rknn_lite.py", line 141, in init_runtime
    async_mode=async_mode, core_mask=core_mask)
  File "rknnlite/api/rknn_runtime.py", line 303, in rknnlite.api.rknn_runtime.RKNNRuntime.__init__
  File "rknnlite/api/rknn_runtime.py", line 382, in rknnlite.api.rknn_runtime.RKNNRuntime._get_target_soc
Exception: Please specify the target in init_runtime!

**Comment by xxxxuee** [comment]
同问

**Comment by RobotiX101** [comment]
Same question

**Comment by shao77622** [comment]
Same question
