### ISSUE TITLE
Can not find dynamic library on RK3566!

### ISSUE THREAD

**Issue by hariag** [rockchip-linux/rknn-toolkit2#16]
root@localhost:/rknn-toolkit2-master/rknn-toolkit-lite2-v1.2.0/examples/inference_with_lite# python3.7 test.py 
--> Load RKNN model
done
--> Init runtime environment
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/rknnlite/api/rknn_lite.py", line 141, in init_runtime
    async_mode=async_mode, core_mask=core_mask)
  File "rknnlite/api/rknn_runtime.py", line 302, in rknnlite.api.rknn_runtime.RKNNRuntime.__init__
  File "rknnlite/api/rknn_runtime.py", line 501, in rknnlite.api.rknn_runtime.RKNNRuntime._load_library
  File "rknnlite/api/rknn_runtime.py", line 477, in rknnlite.api.rknn_runtime.RKNNRuntime._get_rknn_api_lib_path
Exception: Can not find dynamic library on RK3566!

Init runtime environment failed

# uname -ar
Linux fante 4.19.172 #28 SMP Thu Jul 29 19:20:15 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

# cat /proc/device-tree/compatible
rockchip,rk3566-firefly-roc-pcrockchip,rk3566

Did I miss some steps?

**Comment by detectRecog** [comment]
On RK3568, similar errors also occur.

rock@rock-3a:~/rknn-toolkit2-master/rknn-toolkit-lite2-v1.2.0/examples/inference_with_lite$ python3 -u test.py
--> Load RKNN model
done
--> Init runtime environment
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/rock/.local/lib/python3.7/site-packages/rknnlite/api/rknn_lite.py", line 141, in init_runtime
    async_mode=async_mode, core_mask=core_mask)
  File "rknnlite/api/rknn_runtime.py", line 302, in rknnlite.api.rknn_runtime.RKNNRuntime.__init__
  File "rknnlite/api/rknn_runtime.py", line 501, in rknnlite.api.rknn_runtime.RKNNRuntime._load_library
  File "rknnlite/api/rknn_runtime.py", line 477, in rknnlite.api.rknn_runtime.RKNNRuntime._get_rknn_api_lib_path
Exception: Can not find dynamic library on RK3568!

rock@rock-3a:~/rknn-toolkit2-master/rknn-toolkit-lite2-v1.2.0/examples/inference_with_lite$ uname -ar
Linux rock-3a 4.19.193-36-rockchip-gd05f98887579 #rockchip SMP Sat Mar 12 07:35:55 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

rock@rock-3a:~/rknn-toolkit2-master/rknn-toolkit-lite2-v1.2.0/examples/inference_with_lite$ cat /proc/device-tree/compatible
radxa,rock-3-arockchip,rk3568

As errors occur on both 3566 and 3568, I doubt whether this repo is reliable and effective.
