### ISSUE TITLE
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4.0-22dcfef4'

### ISSUE THREAD

**Issue by Raspberry765** [rockchip-linux/rknn-toolkit2#161]
Thank you for nice development kit.

Development enviroment
win11 WSL2
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS)

Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux

I installed all package below.

# base deps
numpy==1.19.5
protobuf==3.12.2
flatbuffers==1.12

# utils
requests==2.27.1
psutil==5.9.0
ruamel.yaml==0.17.4
scipy==1.5.4
tqdm==4.64.0
bfloat16==1.1
opencv-python==4.5.5.64

# base
onnx==1.9.0
onnxoptimizer==0.2.7
onnxruntime==1.10.0
torch==1.10.1
torchvision==0.11.2
tensorflow==2.6.2

I did below.
cd ~/rknn/packages
pip install rknn_toolkit2-1.4.0_22dcfef4-cp38-cp38-linux_x86_64.whl
 
I did the program below.
cd /rknn/examples/onnx/yolov5
python test.py

I caused error below.
Traceback (most recent call last):
  File "test.py", line 239, in <module>
    rknn = RKNN(verbose=True)
  File "/home/takuto/anaconda3/envs/rknn/lib/python3.8/site-packages/rknn/api/rknn.py", line 56, in __init__
    self.rknn_base = RKNNBase(cur_path, verbose)
  File "rknn/api/rknn_base.py", line 75, in rknn.api.rknn_base.RKNNBase.__init__
  File "/home/takuto/anaconda3/envs/rknn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 526, in get_distribution
    dist = get_provider(dist)
  File "/home/takuto/anaconda3/envs/rknn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 398, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/takuto/anaconda3/envs/rknn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 695, in find
    if dist is not None and dist not in req:
  File "/home/takuto/anaconda3/envs/rknn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3204, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/home/takuto/anaconda3/envs/rknn/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 902, in contains
    item = Version(item)
  File "/home/takuto/anaconda3/envs/rknn/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4.0-22dcfef4'

How do I fix?
should I use ubuntu 20.04?

Best regard.

**Comment by Raspberry765** [comment]
I saw the posts in Chinese below.
我第一次做的时候，报了错误，当时提示的是没有这个2-1.4.0-22dcfef4版本，我就跑到conda的环境包下，把所有的2-1.4.0-22dcfef4版本改成了2-1.4.0，才解决这个问题。
[csdn](https://blog.csdn.net/weixin_51651698/article/details/129343955)
Is there any relation to this post?

I translated chenese sentece, but I could not understand.

**Comment by Raspberry765** [comment]
I tried Ubuntu 20.04(WSL2). But, I caused same error.

Best regard..

**Comment by zzd1994** [comment]
我装了2-1.5就没问题了
