### ISSUE TITLE
yolov7 seg在rk3588板上運行結果不良

### ISSUE THREAD

**Issue by laitathei** [rockchip-linux/rknn-toolkit2#199]
使用混合量化後，我在模擬器上可以成功運行，結果如下
![visual_image](https://github.com/rockchip-linux/rknn-toolkit2/assets/56575156/e55ecac5-4507-46ec-a6b8-3203003bab4e)
但在板上使用同樣的後處理程序卻只有馬賽克圖(分割出太多結果)
![visual_image](https://github.com/rockchip-linux/rknn-toolkit2/assets/56575156/f02d8e98-ae09-4f4a-889f-2ce8a5a3d835)

**Comment by laitathei** [comment]
我試了在.cfg文件中使了以下改動
```
custom_quantize_layers:
    'images': float16
```
但出現錯誤
```
E hybrid_quantization_step2: Invalid operands name 'images' in custom_quantize_layers!
W hybrid_quantization_step2: ===================== WARN(1) =====================
E rknn-toolkit2 version: 1.5.0+1fa95b5c
E hybrid_quantization_step2: Catch exception when build RKNN model!
E hybrid_quantization_step2: Traceback (most recent call last):
E hybrid_quantization_step2:   File "rknn/api/rknn_base.py", line 1977, in rknn.api.rknn_base.RKNNBase.hybrid_quantization_step2
E hybrid_quantization_step2:   File "rknn/api/quantizer.py", line 208, in rknn.api.quantizer.Quantizer.load_hybrid_cfg
E hybrid_quantization_step2:   File "rknn/api/quant_utils.py", line 610, in rknn.api.quant_utils.apply_hybrid_cfg
E hybrid_quantization_step2:   File "rknn/api/rknn_log.py", line 112, in rknn.api.rknn_log.RKNNLog.e
E hybrid_quantization_step2: ValueError: Invalid operands name 'images' in custom_quantize_layers!
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
hybrid_quantization_step2 failed!
```
之後我嘗試改動images_int8 layer轉換成float 16, 但它依然不能轉換images layer到float 16
```
W hybrid_quantization_step2: The default input dtype of 'images' is changed from 'float32' to 'int8' in rknn model for performance!
                       Please take care of this change when deploy rknn model with Runtime API!
```
