### ISSUE TITLE
ModuleNotFoundError: No module named 'rknn.api.rknn_log'

### ISSUE THREAD

**Issue by Aismart20170718** [rockchip-linux/rknn-toolkit2#204]
RK3588嵌入式系统ubuntu20.04安装tensorflow2.6.2 请问怎么解决？

Traceback (most recent call last):
  File "changeh5torknn.py", line 2, in <module>
    from rknn.api import RKNN
  File "/usr/local/lib/python3.8/dist-packages/rknn/api/__init__.py", line 1, in <module>
    from rknn.api.rknn import RKNN
  File "/usr/local/lib/python3.8/dist-packages/rknn/api/rknn.py", line 5, in <module>
    from .rknn_log import set_log_level_and_file_path
ModuleNotFoundError: No module named 'rknn.api.rknn_log'

**Comment by charileben** [comment]
@Aismart20170718  were you able to resolve the Module error
if Yes, can you  please specify the process
