### ISSUE TITLE
RK3588S平台，运行rknn-toolkit2/rknn_toolkit_lite2/examples/inference_with_lite/test.py报错 RKNN_ERR_FAIL

### ISSUE THREAD

**Issue by lixunhui** [rockchip-linux/rknn-toolkit2#212]
`--> Load RKNN model
done
--> Init runtime environment
I RKNN: [01:19:04.510] RKNN Runtime Information: librknnrt version: 1.4.0 (a10f100eb@2022-09-09T09:07:14)
I RKNN: [01:19:04.510] RKNN Driver Information: version: 0.8.2
E RKNN: [01:19:04.510] 6, 1
E RKNN: [01:19:04.510] Invalid RKNN model version 6
E RKNN: [01:19:04.510] rknn_init, load model failed!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 875, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

Init runtime environment failed`

**Comment by 0312birdzhang** [comment]
是不是rknpu2和rknn_toolkit2版本不匹配

**Comment by YiQiuZHAO** [comment]
同样的问题，蹲一个解决

**Comment by YiQiuZHAO** [comment]
参考https://blog.csdn.net/qq_16792139/article/details/132319721
把驱动升级一下就好了 @lixunhui

**Comment by wangyu002228** [comment]
> '-->加载 RKNN 模型完成 --> 初始化运行时环境 I RKNN：[01：19：04.510] RKNN 运行时信息：librknnrt 版本：1.4.0 （a10f100eb@2022-09-09T09：07：14） I RKNN：[01：19：04.510] RKNN 驱动程序信息：版本：0.8.2 E RKNN：[01：19：04.510] 6、1 E RKNN：[01：19：04.510] 无效的 RKNN 模型版本 6 E RKNN：[01：19：04.510] rknn_init，加载模型失败！ E 在初始化运行时捕获异常！ E 回溯（最近一次调用最后一次）：文件“/usr/local/lib/python3.8/dist-packages/rknnlite/api/rknn_lite.py”，第 148 行，init_runtime self.rknn_runtime.build_graph（self.rknn_data， self.load_model_in_npu） 文件“rknnlite/api/rknn_runtime.py”，第 875 行，rknnlite.api.rknn_runtime。 RKNNRuntime.build_graph 异常：RKNN 初始化失败。错误代码：RKNN_ERR_FAIL
> 
> 初始化运行时环境失败

请问老师您这个怎么解决的呢

**Comment by YiQiuZHAO** [comment]
> > '-->加载 RKNN 模型完成 --> 初始化运行时环境 I RKNN：[01：19：04.510] RKNN 运行时信息：librknnrt 版本：1.4.0 （a10f100eb@2022-09-09T09：07：14） I RKNN：[01：19：04.510] RKNN 驱动程序信息：版本：0.8.2 E RKNN：[01：19：04.510] 6、1 E RKNN：[01：19：04.510] 无效的 RKNN 模型版本 6 E RKNN：[01：19：04.510] rknn_init，加载模型失败！ E 在初始化运行时捕获异常！ E 回溯（最近一次调用最后一次）：文件“/usr/local/lib/python3.8/dist-packages/rknnlite/api/rknn_lite.py”，第 148 行，init_runtime self.rknn_runtime.build_graph（self.rknn_data， self.load_model_in_npu） 文件“rknnlite/api/rknn_runtime.py”，第 875 行，rknnlite.api.rknn_runtime。 RKNNRuntime.build_graph 异常：RKNN 初始化失败。错误代码：RKNN_ERR_FAIL
> > 初始化运行时环境失败
> 
> 请问老师您这个怎么解决的呢

呢

更新驱动https://github.com/rockchip-linux/rknpu2/releases/tag/v1.5.2
