### ISSUE TITLE
运行examples/onnx/yolov5的demo时出现的错误

### ISSUE THREAD

**Issue by lozenyin** [rockchip-linux/rknn-toolkit2#27]
`
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1590, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/rknn_base.py", line 344, in rknn.api.rknn_base.RKNNBase._generate_rknn
E build:   File "rknn/api/rknn_base.py", line 276, in rknn.api.rknn_base.RKNNBase._export_rknn
E build: ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
Build model failed!

`

我在尝试跟着教程使用这个demo进行模型转换时出现以上报错，libpython3.6m.so.1.0文件在/usr/local/lib文件中。好像是引用不到该文件，这个该如何解决？

**Comment by lozenyin** [comment]
问题解决，原因为环境问题。本人在ubuntu20.04系统中部署，其python3的环境为3.8版本与需求的不符，切换到ubuntu18.04后即可

**Comment by HunterRockchips** [comment]
> 问题解决，原因为环境问题。本人在ubuntu20.04系统中部署，其python3的环境为3.8版本与需求的不符，切换到ubuntu18.04后即可

建议使用docker，这样可以拉齐环境，如果没啥问题可以close该issue

**Comment by goloskokovic** [comment]
@lozenyin what is the inference time(ms) for onnx resnet50v2 on RK3588?

https://github.com/rockchip-linux/rknn-toolkit2/tree/master/examples/onnx/resnet50v2

**Comment by lozenyin** [comment]
@goloskokovic 大约在60ms左右
