### ISSUE TITLE
error: RKNN_ERR_DEVICE_UNAVAILABLE

### ISSUE THREAD

**Issue by dangxusheng** [rockchip-linux/rknn-toolkit2#31]
root@ys:/home/ys/test# python3.7 test_rknn_lite.py 
Linux-aarch64
rockchip,rk3568-evb1-ddr4-v10rockchip,rk3568
host:  RK356x
*************************
None devices connected.
*************************
([], [])
**************************************************
Target platforms filled in RKNN model:         ['RK3568']
Target platforms supported by this RKNN model: ['RK3566', 'RK3568']
**************************************************
OrderedDict([('filled_target_platform', ['RK3568']), ('support_target_platform', ['RK3566', 'RK3568'])])
--> Load RKNN model
done
load rknn model is done.
--> Init runtime environment
E RKNNAPI: rknn_init,  driver open fail!  ret = -12(ERROR_NOT_SUPPORTED)!
E Catch exception when init runtime!
*************************
None devices connected.
*************************
E []
E Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 838, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE

Init runtime environment failed\

====================================
查了下API文档，是i这个原因：
RKNN_ERR_INCOMPATILE_OPTIMIZATION_LEVEL_VERSION（-12） RKNN 模型设置了优化等级的选项， 但是和当前驱动不兼容
请问如何升级NPU驱动，找了半天没找到

**Comment by HunterRockchips** [comment]
rknpu2这个工程里有新的ko
