### ISSUE TITLE
初始化环境失败：Invalid RKNN model version 6

### ISSUE THREAD

**Issue by GitHubmalajava** [rockchip-linux/rknn-toolkit2#316]
--> Init runtime environment
I RKNN: [17:10:15.695] RKNN Runtime Information: librknnrt version: 1.5.0 (e6fe0c678@2023-05-25T08:09:20)
I RKNN: [17:10:15.695] RKNN Driver Information: version: 0.9.0
E RKNN: [17:10:15.696] 6, 4
E RKNN: [17:10:15.696] Invalid RKNN model version 6
E RKNN: [17:10:15.696] rknn_init, load model failed!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/linaro/miniconda3/envs/rk39/lib/python3.9/site-packages/rknnlite/api/rknn_lite.py", line 149, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 921, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID  是因为开发板环境太低了吗

**Comment by Link164735** [comment]
去官网下载最新的librknnrt.so替换/usr/lib下原来的库就行

**Comment by 133673** [comment]
您好我下载最新的so之后并替换还是报这个错为什么呢

**Comment by 133673** [comment]
您好我下载最新的so之后并替换还是报这个错为什么呢
pi@NanoPC-T6-LTS:~/rk_zo/1.6/rknn_model_zoo-1.6.0/install/rk3588_linux_aarch64/rknn_yolov8_demo$ sudo ./rknn_yolov8_demo model/yolov8.rknn model/bus.jpg
load lable ./model/coco_80_labels_list.txt
E RKNN: [16:40:58.701] 6, 1
E RKNN: [16:40:58.701] Invalid RKNN model version 6
E RKNN: [16:40:58.701] rknn_init, load model failed!
rknn_init fail! ret=-1
init_yolov8_model fail! ret=-1 model_path=model/yolov8.rknn
Segmentation fault

**Comment by suse-chen** [comment]
想问一下解决了吗？

**Comment by suse-chen** [comment]
有用

**Comment by exzvm** [comment]
> 去官网下载最新的librknnrt.so替换/usr/lib下原来的库就行

感谢感谢，解决了

**Comment by zhuzhutou** [comment]
/home/forlinx/miniconda3/envs/rknn/bin/python /home/forlinx/workspace/computing_v0.1.0/rknntoolkit_lite2_inference.py 
--> Load RKNN model
done
[ WARN:0@0.450] global loadsave.cpp:275 findDecoder imread_('./dog_224x224.jpg'): can't open/read file: check file path/integrity
--> Init runtime environment
I RKNN: [15:21:07.529] RKNN Runtime Information: librknnrt version: 1.3.0 (c193be371@2022-05-04T20:16:33)
I RKNN: [15:21:07.529] RKNN Driver Information: version: 0.7.2
E RKNN: [15:21:07.530] 6, 1
E RKNN: [15:21:07.530] Invalid RKNN model version 6
E RKNN: [15:21:07.530] rknn_init, load model failed!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/forlinx/miniconda3/envs/rknn/lib/python3.8/site-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 919, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

Init runtime environment failed

运行的是这个代码：https://github.com/rockchip-linux/rknn-toolkit2/tree/master/rknn_toolkit_lite2/examples/dynamic_shape/test.py
librknn_api 和 rknn_server 都是最新的 为什么无法运行啊 这是什么原因
