### ISSUE TITLE
连板推理得时候出现这个报错

### ISSUE THREAD

**Issue by xiefeihua** [rockchip-linux/rknn-toolkit2#330]
I Start adb...
adb: error: cannot bind listener: attempted to listen on unavailable socket type: localabstract:transfer_proxy
E init_runtime: Connect to Device (e1006d4c3b0eae29) Failure (-2), Please check the USB or network connection!
E init_runtime: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2412, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 219, in rknn.api.rknn_runtime.RKNNRuntime.__init__
  File "rknn/api/rknn_platform.py", line 372, in rknn.api.rknn_platform.start_ntp_or_adb
Exception: Init runtime environment failed!

**Comment by xiefeihua** [comment]
我使用adb 是可以正常连接得

**Comment by xiefeihua** [comment]
已经解决 问题是我WSL 开启了网络映射

**Comment by Calsia** [comment]
> 已经解决 问题是我WSL 开启了网络映射

大哥怎么解决啊具体

**Comment by lwcode** [comment]
同好奇是怎么解决的,也是wsl系统

**Comment by Lahahaha** [comment]
开代理软件配置了.wslconfig 文件，导致了这个问题。我把.wslconfig的配置都取消了。
```
[experimental]
#autoMemoryReclaim=gradual
#networkingMode=mirrored
#dnsTunneling=true
#firewall=true
#autoProxy=true
```

然后使用这个工具，将开发板接口连接到 WSL，然后就能正常使用了（这样代理就不能用了，是否有兼得的方法？）:

[usbipd-win](https://github.com/dorssel/usbipd-win/releases
)

![image](https://github.com/user-attachments/assets/74cf9f1c-064d-4198-8bd3-a70c31171c8a)
