### ISSUE TITLE
验证 rknn-toolkit2是否在wsl ubuntu22.04 安装成功问题

### ISSUE THREAD

**Issue by alanxinn** [rockchip-linux/rknn-toolkit2#331]
>>> from rknn.api import RKNN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alanxinn/miniconda3/envs/rknntoolkit2.1.0/lib/python3.10/site-packages/rknn/api/__init__.py", line 1, in <module>
    from rknn.api.rknn import RKNN
  File "/home/alanxinn/miniconda3/envs/rknntoolkit2.1.0/lib/python3.10/site-packages/rknn/api/rknn.py", line 7, in <module>
    from .rknn_base import RKNNBase
  File "rknn/api/rknn_base.py", line 27, in init rknn.api.rknn_base
  File "rknn/api/codegen.py", line 4, in init rknn.api.codegen
  File "/home/alanxinn/miniconda3/envs/rknntoolkit2.1.0/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/alanxinn/miniconda3/envs/rknntoolkit2.1.0/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/alanxinn/miniconda3/envs/rknntoolkit2.1.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
上述python报错 如何解决

**Comment by alanxinn** [comment]
sudo apt-get update
sudo apt-get install libgl1-mesa-glx
安装后即可成功运行
