### ISSUE TITLE
building tensorflow model failed 

### ISSUE THREAD

**Issue by ynjiun** [rockchip-linux/rknn-toolkit2#34]
Hi 

I am able to load a tensorflow model (.pb file) but failed at building the model with the following error message:

```
rknn2$ python rk3566Test.py 
W __init__: rknn-toolkit2 version: 1.3.0-11912b58
--> config model
done
--> Loading tensorflow model
W load_tensorflow: inputs name should be a tensor name instead of node name
W:tensorflow:From /home/paul/rknn2/lib/python3.6/site-packages/rknn/api/rknn.py:108: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W:tensorflow:From /home/paul/rknn2/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py:270: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
done
--> Building model
(op_type:ReduceSum, name:level0/shared/prop0/WarpImageWithHypotheses/warp_and_aggregate_sad/Sum): Inferred shape and existing shape differ in rank: (5) vs (0)
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1638, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 5499, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
E build:   File "rknn/api/ir_graph.py", line 750, in rknn.api.ir_graph.IRGraph.make_model
E build:   File "rknn/api/ir_graph.py", line 62, in rknn.api.ir_graph.IRGraph.infer_shapes
E build:   File "/home/paul/rknn2/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
E build:     inferred_model_str = C.infer_shapes(model_str, check_type)
E build: RuntimeError: Inferred shape and existing shape differ in rank: (5) vs (0)
Build pytorch failed!
```

The code I am running is as below:
```
import numpy as np
import cv2
from rknn.api import RKNN


tf_model = "../models/middlebury_d400.pb"

if __name__ == '__main__':
	
	# Create RKNN object
	rknn = RKNN()
	
	# pre-process config
	print('--> config model')
	rknn.config(mean_values=[[127.5,127.5,127.5,127.5,127.5,127.5]], std_values=[[127.5,127.5,127.5,127.5,127.5,127.5]],target_platform='rk3566') #rk3566: no reorder, make sure the input RGB
	
	print('done')
	
	# Load tensorflow model
	print('--> Loading tensorflow model')
	ret = rknn.load_tensorflow(tf_pb=tf_model,
							inputs=["input"],
							outputs=["reference_output_disparity"],
                            input_size_list=[[1, 226, 500, 6]])
	if ret != 0:
		print('Load model failed!')
		exit(ret)
	print('done')

	# Build model
	print('--> Building model')
	ret = rknn.build(do_quantization=False)
	#ret = rknn.build(do_quantization=True, dataset='./dataset.txt')
	if ret != 0:
		print('Build pytorch failed!')
		exit(ret)
	print('done')

	# Export rknn model
	print('--> Export RKNN model')
	ret = rknn.export_rknn('./model_3566.rknn')
	if ret != 0:
		print('Export model_3566.rknn failed!')
		exit(ret)
	print('done')
	
	#ret = rknn.load_rknn('./model_3566.rknn')
	
	# init runtime environment
	print('--> Init runtime environment')
	#ret = rknn.init_runtime() #run simulator
	ret = rknn.init_runtime(target='rk3566') #run inference on evb board: make sure micro usb connected and run startNPU on evb board

	if ret != 0:
		print('Init runtime environment failed')
		exit(ret)
	print('done')

	print("so far so good....")
	
	# # perf
	print('--> Begin evaluate model performance')
	img=torch.Tensor(226,500,6).random_(0,255)
	perf_results = rknn.eval_perf(inputs=[img])
	print('done')
	
	rknn.release()
```

**Comment by RUIXUEZHAOFENGNIAN** [comment]
Has this problem been solved？
