### ISSUE TITLE
ONNX Build model failed!  IndexError: vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)

### ISSUE THREAD

**Issue by lht0223** [rockchip-linux/rknn-toolkit2#45]
python test.py
W __init__: rknn-toolkit2 version: 1.3.4b4-ad9ac429
--> Config model
done
--> Loading model
done
--> Building model
I base_optimize ...
I base_optimize done.
I 
I fold_constant ...
W build: output: The output shape [1, 0, 6] of model is wrong, fix it to [1, 2160, 6]!
I fold_constant done.
I fold_constant remove nodes = ['ConstantOfShape_17', 'Concat_18', 'Reshape_20', 'Slice_25', 'Transpose_26', 'Reshape_28', 'Cast_29', 'Shape_40', 'Gather_42', 'Shape_43', 'Gather_45', 'Unsqueeze_46', 'Unsqueeze_47', 'Unsqueeze_48', 'Concat_49', 'Cast_61', 'Div_62', 'Cast_63', 'Range_66', 'Unsqueeze_67', 'Concat_68', 'Unsqueeze_69', 'Concat_70', 'Shape_71', 'ConstantOfShape_72', 'Expand_73', 'Tile_74', 'Unsqueeze_75', 'Unsqueeze_76', 'Concat_77', 'Reshape_78', 'Cast_79', 'Cast_80', 'Range_83', 'Unsqueeze_84', 'Concat_85', 'Unsqueeze_86', 'Concat_87', 'Shape_88', 'ConstantOfShape_89', 'Expand_90', 'Tile_91', 'Transpose_92', 'Unsqueeze_93', 'Unsqueeze_94', 'Concat_95', 'Reshape_96', 'Cast_97', 'Add_100', 'Expand_101', 'ConstantOfShape_107', 'Mul_109', 'Equal_110', 'Where_111', 'Expand_112', 'Unsqueeze_113', 'ConstantOfShape_114', 'Mul_116', 'Equal_117', 'Where_118', 'Expand_119', 'Unsqueeze_120', 'ConstantOfShape_121', 'Mul_123', 'Equal_124', 'Where_125', 'Expand_126', 'Unsqueeze_127', 'ConstantOfShape_128', 'Mul_130', 'Equal_131', 'Where_132', 'Expand_133', 'Unsqueeze_134', 'ConstantOfShape_135', 'Mul_137', 'Equal_138', 'Where_139', 'Expand_140', 'Unsqueeze_141', 'Concat_142', 'Reshape_143', 'ScatterND_144', 'Add_146', 'Gather_148', 'Shape_149', 'Expand_150', 'ConstantOfShape_156', 'Mul_158', 'Equal_159', 'Where_160', 'Expand_161', 'Unsqueeze_162', 'ConstantOfShape_163', 'Mul_165', 'Equal_166', 'Where_167', 'Expand_168', 'Unsqueeze_169', 'ConstantOfShape_170', 'Mul_172', 'Equal_173', 'Where_174', 'Expand_175', 'Unsqueeze_176', 'ConstantOfShape_177', 'Mul_179', 'Equal_180', 'Where_181', 'Expand_182', 'Unsqueeze_183', 'ConstantOfShape_184', 'Mul_186', 'Equal_187', 'Where_188', 'Expand_189', 'Unsqueeze_190', 'Concat_191', 'Shape_192', 'Slice_196', 'Concat_197', 'Reshape_198', 'ScatterND_199', 'Gather_201', 'Shape_203', 'Expand_204', 'ConstantOfShape_210', 'Mul_212', 'Equal_213', 'Where_214', 'Expand_215', 'Unsqueeze_216', 'ConstantOfShape_217', 'Mul_219', 'Equal_220', 'Where_221', 'Expand_222', 'Unsqueeze_223', 'ConstantOfShape_224', 'Mul_226', 'Equal_227', 'Where_228', 'Expand_229', 'Unsqueeze_230', 'ConstantOfShape_231', 'Mul_233', 'Equal_234', 'Where_235', 'Expand_236', 'Unsqueeze_237', 'ConstantOfShape_238', 'Mul_240', 'Equal_241', 'Where_242', 'Expand_243', 'Unsqueeze_244', 'Concat_245', 'Shape_246', 'Slice_250', 'Concat_251', 'Reshape_252', 'ScatterND_253', 'Gather_255', 'Shape_257', 'Expand_258', 'ConstantOfShape_264', 'Mul_266', 'Equal_267', 'Where_268', 'Expand_269', 'Unsqueeze_270', 'ConstantOfShape_271', 'Mul_273', 'Equal_274', 'Where_275', 'Expand_276', 'Unsqueeze_277', 'ConstantOfShape_278', 'Mul_280', 'Equal_281', 'Where_282', 'Expand_283', 'Unsqueeze_284', 'ConstantOfShape_285', 'Mul_287', 'Equal_288', 'Where_289', 'Expand_290', 'Unsqueeze_291', 'ConstantOfShape_292', 'Mul_294', 'Equal_295', 'Where_296', 'Expand_297', 'Unsqueeze_298', 'Concat_299', 'Shape_300', 'Slice_304', 'Concat_305', 'Reshape_306', 'ScatterND_307', 'Unsqueeze_308', 'Concat_309', 'Reshape_310', 'Mul_311', 'Unsqueeze_312', 'Concat_313', 'Unsqueeze_315', 'Concat_316', 'ConstantOfShape_340', 'Expand_341', 'Tile_342', 'Reshape_343', 'Cast_344', 'ConstantOfShape_346', 'Expand_347', 'Tile_348', 'Transpose_349', 'Reshape_350', 'Cast_351', 'Add_354', 'Expand_355', 'ConstantOfShape_361', 'Mul_363', 'Equal_364', 'Where_365', 'Expand_366', 'Unsqueeze_367', 'ConstantOfShape_368', 'Mul_370', 'Equal_371', 'Where_372', 'Expand_373', 'Unsqueeze_374', 'ConstantOfShape_375', 'Mul_377', 'Equal_378', 'Where_379', 'Expand_380', 'Unsqueeze_381', 'ConstantOfShape_382', 'Mul_384', 'Equal_385', 'Where_386', 'Expand_387', 'Unsqueeze_388', 'ConstantOfShape_389', 'Mul_391', 'Equal_392', 'Where_393', 'Expand_394', 'Unsqueeze_395', 'Concat_396', 'Reshape_397', 'ScatterND_398', 'Add_400', 'Gather_402', 'Shape_403', 'Expand_404', 'ConstantOfShape_410', 'Mul_412', 'Equal_413', 'Where_414', 'Expand_415', 'Unsqueeze_416', 'ConstantOfShape_417', 'Mul_419', 'Equal_420', 'Where_421', 'Expand_422', 'Unsqueeze_423', 'ConstantOfShape_424', 'Mul_426', 'Equal_427', 'Where_428', 'Expand_429', 'Unsqueeze_430', 'ConstantOfShape_431', 'Mul_433', 'Equal_434', 'Where_435', 'Expand_436', 'Unsqueeze_437', 'ConstantOfShape_438', 'Mul_440', 'Equal_441', 'Where_442', 'Expand_443', 'Unsqueeze_444', 'Concat_445', 'Shape_446', 'Slice_450', 'Concat_451', 'Reshape_452', 'ScatterND_453', 'Gather_455', 'Shape_457', 'Expand_458', 'ConstantOfShape_464', 'Mul_466', 'Equal_467', 'Where_468', 'Expand_469', 'Unsqueeze_470', 'ConstantOfShape_471', 'Mul_473', 'Equal_474', 'Where_475', 'Expand_476', 'Unsqueeze_477', 'ConstantOfShape_478', 'Mul_480', 'Equal_481', 'Where_482', 'Expand_483', 'Unsqueeze_484', 'ConstantOfShape_485', 'Mul_487', 'Equal_488', 'Where_489', 'Expand_490', 'Unsqueeze_491', 'ConstantOfShape_492', 'Mul_494', 'Equal_495', 'Where_496', 'Expand_497', 'Unsqueeze_498', 'Concat_499', 'Shape_500', 'Slice_504', 'Concat_505', 'Reshape_506', 'ScatterND_507', 'Gather_509', 'Shape_511', 'Expand_512', 'ConstantOfShape_518', 'Mul_520', 'Equal_521', 'Where_522', 'Expand_523', 'Unsqueeze_524', 'ConstantOfShape_525', 'Mul_527', 'Equal_528', 'Where_529', 'Expand_530', 'Unsqueeze_531', 'ConstantOfShape_532', 'Mul_534', 'Equal_535', 'Where_536', 'Expand_537', 'Unsqueeze_538', 'ConstantOfShape_539', 'Mul_541', 'Equal_542', 'Where_543', 'Expand_544', 'Unsqueeze_545', 'ConstantOfShape_546', 'Mul_548', 'Equal_549', 'Where_550', 'Expand_551', 'Unsqueeze_552', 'Concat_553', 'Shape_554', 'Slice_558', 'Concat_559', 'Reshape_560', 'ScatterND_561', 'Reshape_562', 'Mul_564']
I 
I correct_ops ...
I correct_ops done.
I 
I fuse_ops ...
I fuse_ops results:
I     fuse_pad_into_maxpool: remove node = ['Pad_31']
I     expand_to_4d_concat: remove node = [], add node = ['Concat_318_1_expand0', 'Concat_318_2_expand0', 'Concat_318_0_expand1']
I     expand_to_4d_concat: remove node = [], add node = ['Concat_568_0_expand0', 'Concat_568_1_expand0', 'Concat_568_0_expand1']
I     remove_invalid_cast: remove node = ['Cast_569']
I     fuse_two_reshape: remove node = ['Reshape_314', 'Reshape_317', 'Concat_318_0_expand1']
I     remove_invalid_reshape: remove node = ['Concat_568_0_expand0']
I     convert_resize_to_deconv: remove node = ['Resize_323'], add node = ['Resize_323_2deconv']
I     expand_to_4d_concat: remove node = [], add node = ['Concat_567_1_expand0', 'Concat_567_2_expand0', 'Concat_567_0_expand1']
I     fuse_two_reshape: remove node = ['Reshape_565', 'Reshape_566', 'Concat_567_0_expand1']
I     remove_invalid_reshape: remove node = ['Concat_568_1_expand0']
I     fold_constant ...
I     fold_constant done.
I 
I fuse_ops done.
I 
I sparse_weight ...
I sparse_weight done.
I 
Analysing : 100%|██████████████████████████████████████████████████| 53/53 [00:00<00:00, 676.21it/s]
Quantizating : 100%|███████████████████████████████████████████████| 53/53 [00:00<00:00, 111.74it/s]
I 
I quant_optimizer ...
I quant_optimizer results:
I     adjust_no_change_node: ['Slice_337', 'Gather_331', 'Slice_59', 'Gather_53', 'MaxPool_32', 'MaxPool_14', 'MaxPool_11', 'MaxPool_8', 'MaxPool_5', 'MaxPool_2']
I     adjust_tanh_sigmoid: ['Sigmoid_332', 'Sigmoid_54']
I quant_optimizer done.
I 
W build: The default input dtype of 'input' is changed from 'float32' to 'int8' in rknn model for performance!
                      Please take care of this change when deploy rknn model with Runtime API!
W build: The default output dtype of 'output' is changed from 'float32' to 'int8' in rknn model for performance!
                      Please take care of this change when deploy rknn model with Runtime API!
I rknn building ...
I RKNN: [17:13:00.089] compress = 0
I RKNN: librknnc version: 1.3.4b4 (96dd06845@2022-06-30T13:10:54)
D RKNN: [17:13:00.128] RKNN is invoked
D RKNN: [17:13:00.248] >>>>>> start: N4rknn16RKNNAddFirstConvE
D RKNN: [17:13:00.248] <<<<<<<< end: N4rknn16RKNNAddFirstConvE
D RKNN: [17:13:00.248] >>>>>> start: N4rknn22RKNNAddReshapeAfterRNNE
D RKNN: [17:13:00.248] <<<<<<<< end: N4rknn22RKNNAddReshapeAfterRNNE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn17RKNNTileGroupConvE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn17RKNNTileGroupConvE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn19RKNNTileFcBatchFuseE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn19RKNNTileFcBatchFuseE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn15RKNNAddConvBiasE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn15RKNNAddConvBiasE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn15RKNNTileChannelE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn15RKNNTileChannelE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn18RKNNPerChannelPrepE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn18RKNNPerChannelPrepE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn21RKNNFuseOptimizerPassE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn21RKNNFuseOptimizerPassE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn11RKNNBnQuantE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn11RKNNBnQuantE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn15RKNNTurnAutoPadE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn15RKNNTurnAutoPadE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn16RKNNInitRNNConstE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn16RKNNInitRNNConstE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn17RKNNInitCastConstE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn17RKNNInitCastConstE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn20RKNNMultiSurfacePassE
D RKNN: [17:13:00.249] <<<<<<<< end: N4rknn20RKNNMultiSurfacePassE
D RKNN: [17:13:00.249] >>>>>> start: N4rknn14RKNNTilingPassE
D RKNN: [17:13:00.250] <<<<<<<< end: N4rknn14RKNNTilingPassE
D RKNN: [17:13:00.250] >>>>>> start: N4rknn23RKNNProfileAnalysisPassE
D RKNN: [17:13:00.250] <<<<<<<< end: N4rknn23RKNNProfileAnalysisPassE
D RKNN: [17:13:00.250] >>>>>> start: OpEmit
D RKNN: [17:13:00.253]       0 -    11       0 -    11       0 -   255 0
D RKNN: [17:13:00.253]       0 -     5       0 -    11       0 -   255 0
D RKNN: [17:13:00.253]       6 -    11       0 -    11       0 -   255 1
D RKNN: [17:13:00.253]       0 -     3       0 -    11       0 -   255 0
D RKNN: [17:13:00.254]       4 -     7       0 -    11       0 -   255 1
D RKNN: [17:13:00.254]       8 -    11       0 -    11       0 -   255 2
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1533, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/rknn_base.py", line 299, in rknn.api.rknn_base.RKNNBase._generate_rknn
E build:   File "rknn/api/rknn_base.py", line 268, in rknn.api.rknn_base.RKNNBase._build_rknn
E build: IndexError: vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)
Build model failed!

**Comment by liujiaxing7** [comment]
Hello, have you solved this problem ?

**Comment by Zhao-hangtian** [comment]
I also encounter this problem. Any body can help please?
