### ISSUE TITLE
rk3588 adb推理初始化runtime报错

### ISSUE THREAD

**Issue by zwtfrost** [rockchip-linux/rknn-toolkit2#75]
--> Init runtime environment
I target set by user is: RK3588
I Starting ntp or adb, target is RK3588
I Device [af3985ee17a6830c] not found in ntb device list.
I Start adb...
I Connect to Device success!
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
D NPUTransfer: Transfer spec = local:transfer_proxy
D NPUTransfer: Transfer interface successfully opened, fd = 4
D RKNNAPI: ==============================================
D RKNNAPI: RKNN VERSION:
D RKNNAPI:   API: 1.2.0 (4c3573e build: 2022-01-13 20:03:13)
D RKNNAPI:   DRV: rknn_server: 1.3.0 (121b661 build: 2022-04-29 11:12:02)
D RKNNAPI:   DRV: rknnrt: 1.3.0 (c193be371@2022-05-04T20:16:33)
D RKNNAPI: ==============================================
E RKNNAPI: rknn_init,  msg_ioctl_ack fail, data_len = 104985, expect 103961!
D NPUTransfer: Transfer client closed, fd = 4
E init_runtime: Catch exception when init runtime!
E init_runtime: Traceback (most recent call last):
E init_runtime:   File "rknn/api/rknn_base.py", line 1916, in rknn.api.rknn_base.RKNNBase.init_runtime
E init_runtime:   File "rknn/api/rknn_runtime.py", line 360, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E init_runtime: Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE
Init runtime environment failed

**Comment by zhanghdcs** [comment]
应保持API和DRV版本一致
