### ISSUE TITLE
ArgMax可以转换，但运行返回None

### ISSUE THREAD

**Issue by AllentDan** [rockchip-linux/rknn-toolkit2#78]
你好。在给 [mmdeploy](https://github.com/open-mmlab/mmdeploy) 支持rockchip， rk3588s 的时候，1.2版本的toolkit2中支持的op包括了ArgMax，但是转模型ok，运行时产生如下错误：
```
I Connect to Device success!
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
D NPUTransfer: Transfer spec = local:transfer_proxy
D NPUTransfer: Transfer interface successfully opened, fd = 18
D RKNNAPI: ==============================================
D RKNNAPI: RKNN VERSION:
D RKNNAPI:   API: 1.2.0 (4c3573e build: 2022-01-13 20:03:13)
D RKNNAPI:   DRV: rknn_server: 1.2.0 (4c3573e build: 2022-01-14 11:09:48)
D RKNNAPI:   DRV: rknnrt: 1.2.0 (1867aec5b@2022-01-14T15:16:40)
D RKNNAPI: ==============================================
D NPUTransfer: The connection has been closed, socket read fd = 18
D NPUTransfer: Transfer client closed, fd = 18
E RKNNAPI: __pthread_recv_msg,  recv(MsgHeader) fail, -9(ERROR_PIPE) < 108!
E RKNNAPI: rknn_outputs_get,  p_ctx->queue_output.size() = 0!
E inference: Catch exception when getting outputs.
E inference: Traceback (most recent call last):
E inference:   File "rknn/api/rknn_base.py", line 2122, in rknn.api.rknn_base.RKNNBase.inference
E inference:   File "rknn/api/rknn_runtime.py", line 491, in rknn.api.rknn_runtime.RKNNRuntime.get_outputs
E inference: Exception: E Get outputs failed, error code: RKNN_ERR_FAIL
```

直接将模型放到C++中运行，报错如下：
```
model input num: 1, output num: 1
input tensors:
  index=0, name=input, n_dims=4, dims=[1, 512, 512, 3], n_elems=786432, size=3145728, fmt=NHWC, type=FP32, qnt_type=AFFINE, zp=0, scale=1.000000
output tensors:
E RKNN: [01:31:19.504] input dtype is undefine!
E RKNN: [01:31:19.504] Unknow dtype to get bytes: 0
  index=0, name=output, n_dims=4, dims=[1, 1, 512, 512], n_elems=262144, size=-262144, fmt=NCHW, type=UNKNOW, qnt_type=AFFINE, zp=0, scale=1.000000
E RKNN: [01:31:20.113] output dtype is undefine!
```
希望得到贵司的快速响应。

**Comment by yuyun2000** [comment]
解决了吗，我也遇到了相同的问题，你可以先在系统模拟器上build，我是可以跑的，目标平台选为3568时的报错就和你相同了

**Comment by yuyun2000** [comment]
佬，回复的真快，贵lab的mmocr俺也用过，略微感觉不如mmdet和mmyolo好用，尤其是文档哈哈

**Comment by AllentDan** [comment]
额，mmocr 人力少点，然后没中文 :bowtie:

**Comment by YaoJiawei329** [comment]
你好，我想请教下如何到处fp32的模型，我默认导出的模型，输入输出节点都是fp16的

**Comment by AllentDan** [comment]
> 你好，我想请教下如何到处fp32的模型，我默认导出的模型，输入输出节点都是fp16的

只有 fp16 和 int8 的，没 fp32

**Comment by yuyun2000** [comment]
佬，我的问题解决了，首先你可以更新到1.5可能问题本身就解决了（1.5的版本更新了好多bug），如果要在1.4的版本下解决，可能需要对原始网络逐层截断，可以定位到网络中哪一层或者哪一部分出了问题，我原来的问题就是网络中有if判断，导致了可能的动态输入，他报错了...你可以试一下，这几周一直在忙毕业的事情忘记回复佬了
