### ISSUE TITLE
rk3588 连板调试报错，adb能连上

### ISSUE THREAD

**Issue by weixiaolian21** [rockchip-linux/rknn-toolkit2#91]
--> Init runtime environment
I target set by user is: rk3588
I Starting ntp or adb, target is RK3588
I Start adb...
I Connect to Device success!
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
D NPUTransfer: Transfer spec = local:transfer_proxy
D NPUTransfer: ERROR: socket read fd = 3, n = -1: Connection reset by peer
D NPUTransfer: Transfer client closed, fd = 3
E RKNNAPI: rknn_init,  server connect fail!  ret = -9(ERROR_PIPE)!
E init_runtime: The rknn_server on the concected device is abnormal, please start the rknn_server on the device according to:
               https://github.com/rockchip-linux/rknpu2/blob/master/rknn_server_proxy.md
W init_runtime: ===================== WARN(5) =====================
E rknn-toolkit2 version: 1.4.0-22dcfef4
E init_runtime: Catch exception when init runtime!
E init_runtime: Traceback (most recent call last):
E init_runtime:   File "rknn/api/rknn_base.py", line 1985, in rknn.api.rknn_base.RKNNBase.init_runtime
E init_runtime:   File "rknn/api/rknn_runtime.py", line 362, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E init_runtime:   File "rknn/api/rknn_log.py", line 113, in rknn.api.rknn_log.RKNNLog.e
E init_runtime: ValueError: The rknn_server on the concected device is abnormal, please start the rknn_server on the device according to:
E init_runtime:                https://github.com/rockchip-linux/rknpu2/blob/master/rknn_server_proxy.md
Init runtime environment failed!

板端log：
start rknn server, version:1.4.0 (bb6dac9 build: 2022-08-29 16:16:56)
0 NNPluginManager loadPlugins(31): loadPlugins
0 NNPluginManager loadPlugins(35): registerPlugin: rknpu!
I NPUTransfer: Starting NPU Transfer Server, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:51)

**Comment by serwansj** [comment]
@weixiaolian21 Did you manage to solve this issue eventually? I am still experiencing the same with version 1.4.0

**Comment by huahuaguigui** [comment]
Did you manage to solve this issue eventually? I am still experiencing the same with version 2.3.0
